### ISSUE TITLE
Make blog articles at /blog/

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/CSS-Tricks-v10#108]
Because 
- better analytics
- search only blog posts

Kinda hard thing to do... must have 301 redirects for all.

**Comment by CWSpear** [comment]
Would it not be possible to have some programatic check for if you go to /a-blog-post/, it checks 
(first if that page exists) for /blog/a-blog-post/ and 301 directs if it exists, 404's if not?

Or what about a whitelist approach? If not one of the other 7 sections in the first part of the URL, not contact, not search-result, then 301 redirect to add in the /blog/ and let WordPress take care of the rest?

This would only work if you know for sure you have a finite number of other sections in the site (and by sections, I mean a part in the first part of the URL, like /snippets/)

**Comment by CWSpear** [comment]
So I know I had that comment in the Lodge section, and it would be awesome to be able to search blog and stuff, and cuz I'm bored like that, I think I do have a good solution.

I got the whitelist version to do via htaccess, but that's kind of hard to maintain and has the disadvantage of routing all 404s through /blog/.

So a better solution:

My personal site is on CodeIgniter for something I want to do down the road (it was static until recently), and the (WordPress) blog is installed at /blog/, but the concept is the same.

With systems that do their own routing, (CI and WP both do this), they have to handle their own 404s. So by hooking into that, we can put in our own code to do a little extra before we report 404.

So I hooked into CI's 404 handling, and before it does what it normally does (set header to 404 and show "page not found" message), I check to see if the page exists if I add /blog/ into it (by checking the http response code), and if it does, I redirect (w/ 301). If it doesn't, I let it do what it normally does.

I think this would work perfectly on your site, and cover your bases SEO-wise after you change all blog posts to be at /blog/.

You can see it in action on my site:

http://cameronspear.com/test/test/ does the normal 404 stuff because http://cameronspear.com/blog/test/test/ does not exist.

http://cameronspear.com/mamp-without-the-app-quick-version/ 301 redirects to http://cameronspear.com/blog/mamp-without-the-app-quick-version/ since the latter exists (using my custom handler).

Anyway, I know that was a lot. I'd have to adapt it to WP, but I know it has a way to handle 404s, so we'd just have to hook into that and most the code's the same. I'm not a WP expert, but I'm sure we could get it to work.

**Comment by CalebKester** [comment]
I was just going to post that it would be nice to search only blog posts. Glad to hear that it'll come down the pipe eventually.

**Comment by CWSpear** [comment]
@CalebKester I have proposed a solution for this and tried to help Chris get this working, but he hasn't seemed interested. It may be a while before it gets fixed.

**Comment by chriscoyier** [comment]
It's gonna happen fellas. Believe it or not I'm pretty busy. I've invested many many hours into this already and have gone down some roads that I didn't like. Having the URL's at the root has some advantages too, so I'm even entirely convinced moving articles to /blog/ is a good idea. I think I'm going to make a new Google Custom Search Engine that has filtered results to remove all the subdirectories and not even bother with the URL changes.
