### ISSUE TITLE
No support for @font-face on Windows Phone

### ISSUE THREAD

**Issue by ack-unter** [chriscoyier/CSS-Tricks-v10#124]
Hi,
I wanted to tell you that there is no support for @font-face on Windows Phone what means that your Icon-Font is replaced by a normal font. As a result I see for example the nav like this:
k Home 9 Forums Q Snippets p Gallery ... and so on
Because I have the same problem on my page I already thought about the solution to target Internet Explorer mobile with
`` 
as you have mentioned it in this post: http://css-tricks.com/iemobile-conditional-comment/ and set the 
[data-icon]:before to display:none;

(the method you used in this post: http://css-tricks.com/html-for-icon-font-usage/ but I experienced the conditional command didn't target my WP7.5 device.

The other idea was (of course) getting a fallback for WP7.5 with jQuery since Javascript is always enabled on this browser. Till now I didn't figured it out how to certainly make this.

I hope this helps you.

**Comment by chriscoyier** [comment]
Thank you Phillipp!

Confirmed that @font-face fails on WP7. See: https://github.com/Modernizr/Modernizr/issues/538

Modernizr is ignoring the issue apparently due to marketshare. I'm sure decisions like that they don't take lightly. 

It would be fairly easy to do

```
<!--[if IEMobile]> 
   [data-icon]:before { display: none; }
<![endif]--> 
```

But I'm just not sure I want to add that little bit of weight to every page on the entire site just for this edge case. Tough call but I'm going to go the way Modernizr went on it.

**Comment by ack-unter** [comment]
Sorry but I add only one thing:
``
doesn't work on my WP7.5 as I already said in the first text. The Code only didn't show up.
But thank you for the quick reply.

**Comment by chriscoyier** [comment]
Ah I see, it DOESN'T work, OK, noted.
