### ISSUE TITLE
Styling inconsistancy

### ISSUE THREAD

**Issue by sethburtonhall** [chriscoyier/CSS-Tricks-v10#158]
http://cl.ly/JWnn

The "Previous" "Next" and "Submit One" seem to be off from the whole design as well as with each other.

Rockin' Screencast

**Comment by chriscoyier** [comment]
I kinda like how they are attached to the top instead of the bottom since they do something different than the submit button. But they are visually similar to each other, and not the 3D style that wouldn't work here. And they attach toward the top which is where the pagination would be, which is essentially what these buttons are doing.

Not to say there couldn't be improvements, but no bug here.

**Comment by sethburtonhall** [comment]
I dig it. Awesome.
