### ISSUE TITLE
Font icon not displaying

### ISSUE THREAD

**Issue by stopsatgreen** [chriscoyier/CSS-Tricks-v10#2]
The icons in the nav bar aren't  showing; the attr(data-icon) is working fine, but Entypo doesn't seem to have loaded. Using Ffx 15 on Ubuntu.

**Comment by jackfranklin** [comment]
Seeing this too, Firefox on Windows 7.

**Comment by Keyamoon** [comment]
It's because Firefox doesn't support cross domain loading of fonts. The solution is to base64 encode and embed the font in CSS.

The current @font-face rule should also be changed. It seems like it has been taken from CSS3please, which doesn't work in IE.

My IcoMoon app can do the base64 encoding and it generates a proper @font-face rule. If you press the settings/gear button in the font tab, you will find the option for embedding.

I would also suggest using anther icon font because entypo doesn't really look good at small sizes. Ideally use a font-size of 16px and an icon font optimized for 16px.

**Comment by OllyHodgson** [comment]
Firefox _does_ support cross-domain loading of fonts. You need to specify access control headers though. See:
- http://stackoverflow.com/questions/5008944/how-to-add-an-access-control-allow-origin-header
- http://logicalfriday.com/2012/03/21/cross-domain-font-woes-in-firefox/
- https://developer.mozilla.org/en-US/docs/HTTP_access_control

**Comment by OllyHodgson** [comment]
Now fixed for Firefox (and IE9).

**Comment by Keyamoon** [comment]
Nice.
