### ISSUE TITLE
Post comments showing email

### ISSUE THREAD

**Issue by joshnh** [chriscoyier/CSS-Tricks-v10#48]
Despite following the profile instructions in your email to Kickstarter backers, leaving comments on posts shows my email instead of my name. Also, I can't find a way to change my name, email, or website for new comments now that I have commented once.

**Comment by chriscoyier** [comment]
I you have posted existing comment that show email, link me here and I'll fix asap. Those aren't attached to your profile (for some dumb reason) and have to be changed manually. 

For the preview thing, you still need to change your "Display name publicly as" setting to be your name instead of email.

Sorry about the trouble there.
