### ISSUE TITLE
The "Design v10" post crashes Safari and Chrome on iOS

### ISSUE THREAD

**Issue by impressivewebs** [chriscoyier/CSS-Tricks-v10#59]
This is a weird bug. The site looks really great on iPhone in both Chrome and Safari, and all pages I visited seem to be fine. But if I try to visit the recent post "Design v10" on either of those browsers on my iPhone, the browser crashes and I have to restart it. I've tried multiple times, with the same result. Only that post seems to do this.

It's iOS 5.1.1 on iPhone 4, if that helps.

It happens after a delay while it's trying to load the page. It seems to be a script trying to load. But why only on that page...?

This problem does not occur on Opera Mini on my iPhone, but Opera mini completely messes up the appearance of the main nav (do you need a bug report for that too?). Also, Safari and Chrome on the iPad (same iOS) do not have any of these problems, so it seems to be iPhone specific.

**Comment by chriscoyier** [comment]
ha yeah, uhmmm pretty BIG problem. Weird that it's just this post that does it. Will be easier(ish) to track down.

**Comment by ryanburnette** [comment]
This probably won't help, but I'll tell my story. I've had a mobile crash problem twice, and both times were weird.

One of the times I had this problem I had not set the overflow property with a good bit of image sticking out into the overflow because the viewport was set to a particular width. So the overflow was off the screen but set to visible. Strange as it was, when I hid the overflow that wasn't visible on the mobile viewport, the crashing stopped.

Another time this happened it was due to jQuery. I had a function bound to some event and had forgotten to return it. So while most browsers could handle the extra memory usage, it was crashing on mobile devices around the time the DOM was hit ready.

If nothing else I guess this story just says that it could really be almost anything. :/

**Comment by chriscoyier** [comment]
Temporary fix in place... comments don't show by default, there is a button to show them. When clicked, it still crashes. but that narrows down the issue to the comments area. Perhaps too much in DOM, too tall, too many shadows, not sure.

**Comment by ryanburnette** [comment]
Maybe it's the styling used on buried comments that causes the crash. There seemed to be a lot going on with that one.

**Comment by ryanburnette** [comment]
@chriscoyier Chris I saw your tweet about it just being the sheer immense height of the post due to comments. I'm surprised. It seems like the browsers (Safari and Chrome) would have a better way of handling that situation.

**Comment by chriscoyier** [comment]
Think this is fixed. Essentially removed some box-shadows and position relative stuff and reduced memory usage. Kinda voodoo stuff. Also there is a button to show comments on mobile now, so won't crash even posts with huge numbers of comments.
