### ISSUE TITLE
Nav Close Button

### ISSUE THREAD

**Issue by Digi59404** [chriscoyier/CSS-Tricks-v10#66]
When the navigation is brought down on the mobile size the close button is too small to properly receive a tap.

**Comment by chriscoyier** [comment]
You're right, it's very small, but it's doable. I kinda struggled with this because there is so little room to work with having a big ol' close button is probably worse. Not having a close button at all is an issue since once you've seen the expanded nav, there really is no big reason to close it, you can still scroll around.
