### ISSUE TITLE
h2 elements nearly unreadable in chrome...

### ISSUE THREAD

**Issue by KennyGScott** [chriscoyier/CSS-Tricks-v10#90]
When viewing the forums I am having major trouble reading the post titles, maybe I'm blind but just in case here is what I am seeing: <br><img src="http://i45.tinypic.com/11kaxi1.jpg">

**Comment by ryanburnette** [comment]
What's your OS?

**Comment by KennyGScott** [comment]
WIndows 7

**Comment by tycooon** [comment]
+1 have the same problem
By the way main-nav looks bad too

<img src="http://dl.dropbox.com/u/8231702/screenshots/screen120909-121628.png">

**Comment by ryanburnette** [comment]
Yea I just loaded up Windows 7 and Chrome to check. There are several places where the fonts render a bit yuckily. I don't remember seeing this on my normal Windows XP + Chrome test machine. I'll go check there too.

**Comment by masslevel** [comment]
In my opinion this happens in Chrome / Windows 7 because Chrome still doesn't use Microsoft's DirectWrite Text Rendering. It's a common issue with @fontface in Chrome / Windows and text anti-aliasing tends to look really jaggy. In Firefox / Windows css-tricks.com looks very smooth and crisp. Mozilla implemented DirectWrite in Firefox 4 as far as I remember. But everything should be fine on Mac.

**Comment by impressivewebs** [comment]
Just to add to this, this is happening all over the home page on Chrome Win7, but not on FF.

Here's a screenr I did showing the jagged fonts on the home page:

http://www.screenr.com/IMJ8 (View full screen in HD to see it clearly)

**Comment by chriscoyier** [comment]
It certainly looks a lot better when the font is bigger. We may still be in a place with a lot of web fonts where browser sniffing (or at least platform sniffing) is in order and just not serving custom fonts to Windows. Assuming there is something that looks acceptable otherwise, in my case, probably Arial on Windows.

I'm going to make the size adjustment and then close this. I'm going to let it ride for a little bit hoping that the situation improves in Chrome/Windows fairly soon, and if not, I'll do something more drastic.
